package com.example.cseproject.Enum;

public enum DemographicGroup {
    WHITE, AFRICAN_AMERICAN,  ASIAN, NATIVE_HAWAIIAN_AND_OTHER_PACIFIC_ISLANDER,
    TWO_OR_MORE_RACES, AMERICAN_INDIAN_AND_ALASKA_NATIVE, SOME_OTHER_RACE
}
